In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/vaibhavkumar11/hindi-english-parallel-corpus/hindi_english_parallel.csv

In [3]:
fd=pd.read_csv("/kaggle/input/datasets/vaibhavkumar11/hindi-english-parallel-corpus/hindi_english_parallel.csv")
fd.shape

(1561841, 2)

In [4]:
df = fd.head(50000)

In [5]:
df.shape

(50000, 2)

In [6]:
df['hindi'].dtype

dtype('O')

In [7]:
df['hindi']=df['hindi'].astype(str)
df['english']=df['english'].astype(str)

/tmp/ipykernel_58/2033893278.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hindi']=df['hindi'].astype(str)
/tmp/ipykernel_58/2033893278.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['english']=df['english'].astype(str)

In [8]:
df['hindi'].dtype

dtype('O')

In [9]:
df.dropna()

,hindi,english
0,अपने अनुप्रयोग को पहुंचनीयता व्यायाम का लाभ दें,Give your application an accessibility workout
1,एक्सेर्साइसर पहुंचनीयता अन्वेषक,Accerciser Accessibility Explorer
2,निचले पटल के लिए डिफोल्ट प्लग-इन खाका,The default plugin layout for the bottom panel
3,ऊपरी पटल के लिए डिफोल्ट प्लग-इन खाका,The default plugin layout for the top panel
4,उन प्लग-इनों की सूची जिन्हें डिफोल्ट रूप से नि...,A list of plugins that are disabled by default
...,...,...
49995,ऑडियो जाँच,Audio test
49996,मूक,Silent
49997,वीडियो जाँचScreencast,Video test
49998,दीवाना,Crazy
49999,स्क्रीनकास्ट,Screencast

In [10]:

df.isnull().sum()

hindi      0
english    0
dtype: int64

In [11]:
df['english']="<Start> " + df['english'] + " <End>"

/tmp/ipykernel_58/2729831932.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['english']="<Start> " + df['english'] + " <End>"

In [12]:
df.head()

,hindi,english
0,अपने अनुप्रयोग को पहुंचनीयता व्यायाम का लाभ दें,<Start> Give your application an accessibility...
1,एक्सेर्साइसर पहुंचनीयता अन्वेषक,<Start> Accerciser Accessibility Explorer <End>
2,निचले पटल के लिए डिफोल्ट प्लग-इन खाका,<Start> The default plugin layout for the bott...
3,ऊपरी पटल के लिए डिफोल्ट प्लग-इन खाका,<Start> The default plugin layout for the top ...
4,उन प्लग-इनों की सूची जिन्हें डिफोल्ट रूप से नि...,<Start> A list of plugins that are disabled by...

In [13]:
def tokenize(sentence):
    return sentence.split()

In [14]:
print(tokenize(df['hindi'].iloc[0]))
print(tokenize(df['english'].iloc[0]))

['अपने', 'अनुप्रयोग', 'को', 'पहुंचनीयता', 'व्यायाम', 'का', 'लाभ', 'दें']
['<Start>', 'Give', 'your', 'application', 'an', 'accessibility', 'workout', '<End>']

In [15]:

from collections import Counter

hindi_counter=Counter()
english_counter=Counter()

for  sentence in df['hindi']:
    hindi_counter.update(tokenize(sentence))
    
for  sentence in df['english']:
    english_counter.update(tokenize(sentence))

In [16]:
print(english_counter['the'])

10245

In [17]:
special_tokens = [
    "<PAD>",
    "<UNK>"
]

In [18]:
MAX_VOCAB = 20000

hindi_words = [
    word
    for word, _ in hindi_counter.most_common(MAX_VOCAB)
]

hindi_vocab = {
    token: idx
    for idx, token in enumerate(
        special_tokens + hindi_words
    )
}

In [19]:
print(list(hindi_counter.keys())[:20])

['अपने', 'अनुप्रयोग', 'को', 'पहुंचनीयता', 'व्यायाम', 'का', 'लाभ', 'दें', 'एक्सेर्साइसर', 'अन्वेषक', 'निचले', 'पटल', 'के', 'लिए', 'डिफोल्ट', 'प्लग-इन', 'खाका', 'ऊपरी', 'उन', 'प्लग-इनों']

In [20]:
MAX_VOCAB = 20000

english_words = [
    word
    for word, _ in english_counter.most_common(MAX_VOCAB)
]

english_vocab = {
    token: idx
    for idx, token in enumerate(
        special_tokens + english_words
    )
}

In [21]:
def numericalize(sentence, vocab):
    return [
        vocab.get(word, vocab["<UNK>"])
        for word in sentence.split()
    ]

In [22]:
sample_hindi = df["hindi"].iloc[0]
sample_english = df["english"].iloc[0]

print(sample_hindi)
print(numericalize(sample_hindi, hindi_vocab))

print(sample_english)
print(numericalize(sample_english, english_vocab))

अपने अनुप्रयोग को पहुंचनीयता व्यायाम का लाभ दें
[381, 152, 3, 758, 2774, 7, 2775, 247]
<Start> Give your application an accessibility workout <End>
[2, 2007, 56, 295, 31, 652, 3292, 3]

In [24]:
from torch.utils.data import Dataset

class TranslationDataset(Dataset):

    def __init__(self, df, hindi_vocab, english_vocab):
        self.df = df
        self.hindi_vocab = hindi_vocab
        self.english_vocab = english_vocab

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):

        hindi_sentence = self.df.iloc[idx]["hindi"]
        english_sentence = self.df.iloc[idx]["english"]

        hindi_ids = numericalize(
            hindi_sentence,
            self.hindi_vocab
        )

        english_ids = numericalize(
            english_sentence,
            self.english_vocab
        )

        return hindi_ids, english_ids

In [25]:
dataset = TranslationDataset(
    df,
    hindi_vocab,
    english_vocab
)

In [26]:
import torch
from torch.nn.utils.rnn import pad_sequence

PAD_IDX_HINDI = hindi_vocab["<PAD>"]
PAD_IDX_ENGLISH = english_vocab["<PAD>"]

def collate_fn(batch):

    hindi_sentences = []
    english_sentences = []

    for hindi_ids, english_ids in batch:

        hindi_sentences.append(
            torch.tensor(hindi_ids, dtype=torch.long)
        )

        english_sentences.append(
            torch.tensor(english_ids, dtype=torch.long)
        )

    hindi_padded = pad_sequence(
        hindi_sentences,
        batch_first=True,
        padding_value=PAD_IDX_HINDI
    )

    english_padded = pad_sequence(
        english_sentences,
        batch_first=True,
        padding_value=PAD_IDX_ENGLISH
    )

    return hindi_padded, english_padded

In [27]:
from torch.utils.data import DataLoader

dataloader = DataLoader(
    dataset,
    batch_size=8,
    shuffle=True,
    collate_fn=collate_fn
)

In [28]:
import torch
import torch.nn as nn

class Encoder(nn.Module):

    def __init__(
        self,
        input_dim,
        emb_dim,
        hidden_dim
    ):
        super().__init__()

        self.embedding = nn.Embedding(
            input_dim,
            emb_dim
        )

        self.lstm = nn.LSTM(
            emb_dim,
            hidden_dim,
            batch_first=True
        )

    def forward(self, x):

        embedded = self.embedding(x)

        outputs, (hidden, cell) = self.lstm(
            embedded
        )

        return outputs, hidden, cell

In [29]:
encoder = Encoder(
    input_dim=len(hindi_vocab),
    emb_dim=256,
    hidden_dim=512
)

In [30]:
for hindi_batch, english_batch in dataloader:

    outputs, hidden, cell = encoder(
        hindi_batch
    )

    print(outputs.shape)
    print(hidden.shape)

    break

torch.Size([8, 5, 512])
torch.Size([1, 8, 512])

In [31]:
class Attention(nn.Module):

    def __init__(self, hidden_dim):
        super().__init__()

        self.attn = nn.Linear(
            hidden_dim * 2,
            hidden_dim
        )

        self.v = nn.Linear(
            hidden_dim,
            1,
            bias=False
        )

    def forward(
        self,
        hidden,
        encoder_outputs
    ):

        src_len = encoder_outputs.shape[1]

        hidden = hidden.squeeze(0)

        hidden = hidden.unsqueeze(1).repeat(
            1,
            src_len,
            1
        )

        energy = torch.tanh(
            self.attn(
                torch.cat(
                    (hidden, encoder_outputs),
                    dim=2
                )
            )
        )

        attention = self.v(
            energy
        ).squeeze(2)

        return torch.softmax(
            attention,
            dim=1
        )

In [34]:
class Decoder(nn.Module):

    def __init__(
        self,
        output_dim,
        emb_dim,
        hidden_dim,
        attention
    ):
        super().__init__()

        self.embedding = nn.Embedding(
            output_dim,
            emb_dim
        )

        self.lstm = nn.LSTM(
            emb_dim + hidden_dim,
            hidden_dim,
            batch_first=True
        )

        self.fc = nn.Linear(
            hidden_dim,
            output_dim
        )

        self.attention = attention

    def forward(
        self,
        x,
        hidden,
        cell,
        encoder_outputs
    ):

        # x: [batch_size]
        x = x.unsqueeze(1)

        # embedded: [batch_size, 1, emb_dim]
        embedded = self.embedding(x)

        # attention_weights: [batch_size, src_len]
        attention_weights = self.attention(
            hidden[-1],
            encoder_outputs
        )

        # context: [batch_size, 1, hidden_dim]
        context = torch.bmm(
            attention_weights.unsqueeze(1),
            encoder_outputs
        )

        # [batch_size, 1, emb_dim + hidden_dim]
        rnn_input = torch.cat(
            (embedded, context),
            dim=2
        )

        output, (hidden, cell) = self.lstm(
            rnn_input,
            (hidden, cell)
        )

        prediction = self.fc(
            output.squeeze(1)
        )

        return prediction, hidden, cell

In [35]:
class Seq2Seq(nn.Module):

    def __init__(
        self,
        encoder,
        decoder
    ):
        super().__init__()

        self.encoder = encoder
        self.decoder = decoder

    def forward(
        self,
        src,
        trg
    ):

        batch_size = trg.shape[0]
        trg_len = trg.shape[1]
        vocab_size = self.decoder.fc.out_features

        outputs = torch.zeros(
            batch_size,
            trg_len,
            vocab_size
        ).to(src.device)

        encoder_outputs, hidden, cell = self.encoder(src)

        x = trg[:, 0]

        for t in range(1, trg_len):

            prediction, hidden, cell = self.decoder(
                x,
                hidden,
                cell,
                encoder_outputs
            )

            outputs[:, t] = prediction

            x = trg[:, t]

        return outputs

In [37]:
encoder = Encoder(
    len(hindi_vocab),
    256,
    512
)
attention = Attention(512)

decoder = Decoder(
    len(english_vocab),
    256,
    512,
    attention=attention
)

model = Seq2Seq(
    encoder,
    decoder
)

In [38]:
for src, trg in dataloader:

    outputs = model(
        src,
        trg
    )

    print(outputs.shape)

    break

torch.Size([8, 9, 6915])

In [39]:
criterion = nn.CrossEntropyLoss(
    ignore_index=english_vocab["<PAD>"]
)

In [40]:
import torch.optim as optim

optimizer = optim.Adam(
    model.parameters(),
    lr=0.001
)

In [41]:
device = torch.device(
    "cuda" if torch.cuda.is_available()
    else "cpu"
)

model = model.to(device)

In [42]:
num_epochs = 10

for epoch in range(num_epochs):

    model.train()

    epoch_loss = 0

    for src, trg in dataloader:

        src = src.to(device)
        trg = trg.to(device)

        optimizer.zero_grad()

        output = model(
            src,
            trg
        )

        output_dim = output.shape[-1]

        output = output[:, 1:, :]

        trg = trg[:, 1:]

        output = output.reshape(
            -1,
            output_dim
        )

        trg = trg.reshape(-1)

        loss = criterion(
            output,
            trg
        )

        loss.backward()

        optimizer.step()

        epoch_loss += loss.item()

    print(
        f"Epoch {epoch+1}: "
        f"{epoch_loss/len(dataloader):.4f}"
    )

Epoch 1: 2.2600
Epoch 2: 0.4405
Epoch 3: 0.2862
Epoch 4: 0.2296
Epoch 5: 0.1994
Epoch 6: 0.1828
Epoch 7: 0.1693
Epoch 8: 0.1614
Epoch 9: 0.1521
Epoch 10: 0.1466